### ISSUE TITLE
sync command - SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by lovasoa** [openode-io/openode-cli#15]
Hello,
 I recently got the following error on CI, so I thought I would report it : 

```
> openode sync && openode restart

[Sat Mar 21 2020 19:04:09 GMT+0000 (Coordinated Universal Time)] -  [+] Authentication valid.

- 

Processing for canada

SyntaxError: Unexpected token o in JSON at position 1

    at JSON.parse (<anonymous>)

    at execSyncFiles (/home/travis/build/lovasoa/whitebophir/node_modules/openode/modules/deploy.js:276:24)

    at process._tickCallback (internal/process/next_tick.js:68:7)

[ { SyntaxError: Unexpected token o in JSON at position 1

      at JSON.parse (<anonymous>)

      at execSyncFiles (/home/travis/build/lovasoa/whitebophir/node_modules/openode/modules/deploy.js:276:24)

      at process._tickCallback (internal/process/next_tick.js:68:7) location: 'canada' } ]

[Sat Mar 21 2020 19:04:42 GMT+0000 (Coordinated Universal Time)] -  [+] Authentication valid.

- 

Processing for canada

[ { result: 'success', deploymentId: 1816, location: 'canada' } ]
```

It happened only one, and relaunching the command did not reproduce the error.

**Comment by DatMayo** [comment]
Looks like there was a communication issue and your openode client got a maliformed json back. Does the error occur more often or only once?

**Comment by lovasoa** [comment]
I have currently only seen it once. And yes, it looks like an error on your backend. But anyway, the cli tool should be able to handle the error gracefully.

**Comment by martinlevesque** [comment]
Hi,

Thanks for reporting. Note that this is a deployment done using the legacy method, we upgraded recently, please see https://www.openode.io/docs/installation/upgrade.md

Will see if it happens also using the new system.

**Comment by martinlevesque** [comment]
Thanks, will investigate this asap.

**Comment by martinlevesque** [comment]
Improvement done (graceful exit with more log details) in the new CLI version (2.0.16), npm i -g openode to upgrade

Keeping it open to monitor

**Comment by lovasoa** [comment]
I updated the cli tool and redeployed, but this time the deploy worked. Did you investigate the issue on the server side ?

**Comment by martinlevesque** [comment]
No, if it still occur we will have more details and look at it again. It seemed to be happening during peak hours, and a "3 seconds" timeout was present and has been removed in the new version.
