### ISSUE TITLE
Internal Server Error - Every Command

### ISSUE THREAD

**Issue by RamonRobben** [openode-io/openode-cli#25]
When I run any command in openode cli it returns:

```
[Fri Apr 24 2020 12:30:20 GMT+0200 (Central European Summer Time)] -  [+] Authentication valid.
prompt: sitename:  sitename
[Fri Apr 24 2020 12:31:11 GMT+0200 (Central European Summer Time)] -  creating website...
[Fri Apr 24 2020 12:31:11 GMT+0200 (Central European Summer Time)] -  { status: 500, error: 'Internal Server Error' }
```

even when running a command like _openode list-templates_
My openode cli version is openode@2.0.18
My nodejs version is v12.13.0

**Comment by RamonRobben** [comment]
I fixed my error by creating the website on the openode dashboard and then running commands in the CLI.

**Comment by martinlevesque** [comment]
Hey,

Sorry for the delay. Are you still having similar issues?
