### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:349

### ISSUE THREAD

**Issue by togoenvogue** [openode-io/openode-cli#28]
Hello,

I have been trying since to use the console on my live instances, but none worked.
I even copied and paste the example in the documentation, but it didn't work.

> openode exec ls -la
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"openode\": executable file not found in $PATH": unknown STDERR:
> command terminated with exit code 126

Could somebody help?

Thank you

**Comment by martinlevesque** [comment]
Hey,

More likely the issue is that

> openode exec ls -la

Please try with quotes, openode exec "ls -la"
