### ISSUE TITLE
fork/replace prompt package - Warning with node 14, Warning: Accessing non-existent property 'padLevels'

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-cli#33]
More likely due to https://github.com/flatiron/prompt/issues/199

**Comment by lvenier** [comment]
Correct. I have checked and you're right. It comes from winston version imported by prompt.
https://www.npmjs.com/package/prompt is 4 years old. Probablity to fix is low.

**Comment by martinlevesque** [comment]
Will look to fork the package or replace it as soon as possible.

**Comment by lvenier** [comment]
@martinlevesque : you should check [inquirer](https://www.npmjs.com/package/inquirer)
might do the job.
