### ISSUE TITLE
Fix issues reported by a linter 

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-cli#36]
https://www.npmjs.com/package/standard

**Comment by lvenier** [comment]
Why not https://www.npmjs.com/package/eslint ?

**Comment by martinlevesque** [comment]
I don't mind using either. Does eslint --init provides "right" rules?

**Comment by lvenier** [comment]
it depends what is "right". it's very customizable and lots of plugins. 
Im lazy too and use the same eslintrc.json files on all the projects. I would recommend the same. :)

**Comment by martinlevesque** [comment]
If it's short, can you paste it here please

**Comment by lvenier** [comment]
better this way : eslint simple config #38
