### ISSUE TITLE
Using a token for the sync, reload, and sync-n-reload commands

### ISSUE THREAD

**Issue by sunabozu** [openode-io/openode-cli#4]
I'm not sure if I'm getting it right, but is there a reason why the `-t` key doesn't work with the `restart` command? Or maybe I'm using it wrong:

```openode restart -t TOKEN -s SITENAME```

**Comment by martinlevesque** [comment]
Hey,

Currently only the deploy subcommand (openode deploy) supports it. So you are right.

But it would make sense to support -t and -s for all authentication-based subcommand, we will add it soon.

**Comment by martinlevesque** [comment]
This command no more exists - will soon add a doc detailing on how to set a token with CI/CD
