### ISSUE TITLE
Improve authentication performance

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-cli#42]
modules/auth.js

**Comment by lvenier** [comment]
@martinlevesque: I am not sure if it makes sense to verify the token on every cmd. why not handling 401/403 from the cli ?

**Comment by martinlevesque** [comment]
Good point. However note that it has some logic around it currently - if the token is invalid it will prompt for login or signup.
Note that this is done pretty quickly, and can also add caching in our API if it's too "slow" while making lots of CLI commands.

**Comment by lvenier** [comment]
I believe we can have similar logic: if .openode file is not present then login.
if present then handle api response code (40X vs 20X). Just a proposal as I do not yet have the full knowledge of the client.

As a test I remove the auth and it decreases command response by 0.3s. When you run it on 100 containers it starts to make a difference. it also removed 100 calls from the openode api. :)

**Comment by martinlevesque** [comment]
Ok, will look at it, for now I renamed the task to be more general

**Comment by martinlevesque** [comment]
minor improvement using a light route for now.
