### ISSUE TITLE
I can't deploy

### ISSUE THREAD

**Issue by Naaach** [openode-io/openode-cli#47]
Hi, every time i trry to deploy any app the CLI shows the same error

`
openode deploy -s tasks-connector
[Thu Jun 04 2020 11:43:41 GMT+0200 (Hora de verano romance)] -  [+] Authentication valid.
| { FetchError: invalid json response body at https://api.openode.io/instances/tasks-connector/changes reason: Unexpected end of JSON input
    at C:\Users\Nacho\AppData\Roaming\npm\node_modules\openode\node_modules\node-fetch\lib\index.js:272:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'invalid json response body at https://api.openode.io/instances/tasks-connector/changes reason: Unexpected end of JSON input',
  type: 'invalid-json' }
{ FetchError: invalid json response body at https://api.openode.io/instances/tasks-connector/changes reason: Unexpected end of JSON input
    at C:\Users\Nacho\AppData\Roaming\npm\node_modules\openode\node_modules\node-fetch\lib\index.js:272:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'invalid json response body at https://api.openode.io/instances/tasks-connector/changes reason: Unexpected end of JSON input',
  type: 'invalid-json' }
No deployment attached... exiting
`

**Comment by martinlevesque** [comment]
Please use the administration support or reddit for technical issues.
