### ISSUE TITLE
erase-all command should probably have a confirmation prompt

### ISSUE THREAD

**Issue by Darkle** [openode-io/openode-cli#48]
Since the `openode erase-all` command also erases persistand volumes - which may contain data not stored in source control, I think it might be a good idea for this command to have a confirmation prompt. It could say something like **"Are you sure you want to erase-all? (this will also erase any persistant volumes) [N/y]"**.

**Comment by martinlevesque** [comment]
Hey,

Thanks for the suggestion.

Note that this command now only clear the files in a temporarily location just before building the image which is then deployed. So normally no content is lost.
Perhaps the command description should be clarified instead, will look at it.

**Comment by martinlevesque** [comment]
Updated in the readme
