### ISSUE TITLE
Return a non-zero exit code when a deployment fails

### ISSUE THREAD

**Issue by lovasoa** [openode-io/openode-cli#6]
Currently, when `openode` fails, it outputs an error message on the standard output, but returns with a `0` (success) [exit code](https://en.wikipedia.org/wiki/Exit_status).

<details>

Example failed deployment

```
$ npx openode deploy
[Tue Nov 27 2018 16:22:55 GMT+0100 (Central European Standard Time)] -  [+] Authentication valid.
⠧ Sending files (trial 1) - file=./.travis.yml size=92 operation=M
Sending files (trial 1) - file=./Dockerfile size=926 operation=C
⠏ 2/2
[ { location: 'canada',
    result: { status: 'Operation in progress' } } ]
Checking credits available
Preparing repository
Clearing website container
Preparing website image...
Sending build context to Docker daemon  3.92 MB
[...]
Successfully built 8e9c6e91648d
Spawning website container...

[ { 'HTTP(S) port listening': true,
    valid: true,
    'Help Links': {},
    Error: 'Unable to create the node docker',
    buildDuration: 8.16,
    'Boot Logs': '' } ]

$ echo $?
0
```

</details>

This is especially annoying when using the openode cli in a CI environment that uses the command's return code to determine the build status.

**Comment by martinlevesque** [comment]
Hi!

Thanks for the feedback. Will look at it as soon as possible.

**Comment by martinlevesque** [comment]
In the newest version it will exit with non zero code when you "openode deploy".

Thanks

**Comment by lovasoa** [comment]
Thank you :+1:
