### ISSUE TITLE
Ignoring doesn't seem to work

### ISSUE THREAD

**Issue by JosteinKringlen** [openode-io/openode-cli#7]
Deploying to openode seems to push `node_modules/`, `.idea/`, `.git/` etc., even though the dirs are added to `.openodeignore`.

It looks like `.openodeignore` might actually get ignored itself, as it is not listed in the container at all when running `openode cmd "ls -la"`

**Comment by martinlevesque** [comment]
Hi!

Seems pretty strange. Could you provide the following information via the support form ( https://www.openode.io/admin/support/ ) in the administration:

- The CLI version: type "openode -V"
- Your node version: node -v
- Your operating system.
- The log output when you ran "openode deploy".
- The files listing of your local files.
- The .openodeignore file content.

Thanks!

**Comment by JosteinKringlen** [comment]
Done!

**Comment by martinlevesque** [comment]
We just fixed the issue, get the latest (1.8.6, run the following npm i -g openode), let me know if it now works.

It's indeed a regression related to a recent upgrade of our packages.

Thanks!

**Comment by JosteinKringlen** [comment]
Great, everything seems to be working fine now! 😃

Thanks alot!
